package com.xuren.oa.entity;

import org.apache.ibatis.type.Alias;

@Alias("Department")
public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.sn
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.NAME
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.address
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.sn
     *
     * @return the value of department.sn
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.sn
     *
     * @param sn the value for department.sn
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.NAME
     *
     * @return the value of department.NAME
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.NAME
     *
     * @param name the value for department.NAME
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.address
     *
     * @return the value of department.address
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.address
     *
     * @param address the value for department.address
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}