package com.xuren.oa.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExpenseAccountDealExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public ExpenseAccountDealExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdIsNull() {
            addCriterion("expense_account_id is null");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdIsNotNull() {
            addCriterion("expense_account_id is not null");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdEqualTo(Integer value) {
            addCriterion("expense_account_id =", value, "expenseAccountId");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdNotEqualTo(Integer value) {
            addCriterion("expense_account_id <>", value, "expenseAccountId");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdGreaterThan(Integer value) {
            addCriterion("expense_account_id >", value, "expenseAccountId");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("expense_account_id >=", value, "expenseAccountId");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdLessThan(Integer value) {
            addCriterion("expense_account_id <", value, "expenseAccountId");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdLessThanOrEqualTo(Integer value) {
            addCriterion("expense_account_id <=", value, "expenseAccountId");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdIn(List<Integer> values) {
            addCriterion("expense_account_id in", values, "expenseAccountId");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdNotIn(List<Integer> values) {
            addCriterion("expense_account_id not in", values, "expenseAccountId");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdBetween(Integer value1, Integer value2) {
            addCriterion("expense_account_id between", value1, value2, "expenseAccountId");
            return (Criteria) this;
        }

        public Criteria andExpenseAccountIdNotBetween(Integer value1, Integer value2) {
            addCriterion("expense_account_id not between", value1, value2, "expenseAccountId");
            return (Criteria) this;
        }

        public Criteria andDealSnIsNull() {
            addCriterion("deal_sn is null");
            return (Criteria) this;
        }

        public Criteria andDealSnIsNotNull() {
            addCriterion("deal_sn is not null");
            return (Criteria) this;
        }

        public Criteria andDealSnEqualTo(String value) {
            addCriterion("deal_sn =", value, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnNotEqualTo(String value) {
            addCriterion("deal_sn <>", value, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnGreaterThan(String value) {
            addCriterion("deal_sn >", value, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnGreaterThanOrEqualTo(String value) {
            addCriterion("deal_sn >=", value, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnLessThan(String value) {
            addCriterion("deal_sn <", value, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnLessThanOrEqualTo(String value) {
            addCriterion("deal_sn <=", value, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnLike(String value) {
            addCriterion("deal_sn like", value, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnNotLike(String value) {
            addCriterion("deal_sn not like", value, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnIn(List<String> values) {
            addCriterion("deal_sn in", values, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnNotIn(List<String> values) {
            addCriterion("deal_sn not in", values, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnBetween(String value1, String value2) {
            addCriterion("deal_sn between", value1, value2, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealSnNotBetween(String value1, String value2) {
            addCriterion("deal_sn not between", value1, value2, "dealSn");
            return (Criteria) this;
        }

        public Criteria andDealTimeIsNull() {
            addCriterion("deal_time is null");
            return (Criteria) this;
        }

        public Criteria andDealTimeIsNotNull() {
            addCriterion("deal_time is not null");
            return (Criteria) this;
        }

        public Criteria andDealTimeEqualTo(Date value) {
            addCriterion("deal_time =", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeNotEqualTo(Date value) {
            addCriterion("deal_time <>", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeGreaterThan(Date value) {
            addCriterion("deal_time >", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("deal_time >=", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeLessThan(Date value) {
            addCriterion("deal_time <", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeLessThanOrEqualTo(Date value) {
            addCriterion("deal_time <=", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeIn(List<Date> values) {
            addCriterion("deal_time in", values, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeNotIn(List<Date> values) {
            addCriterion("deal_time not in", values, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeBetween(Date value1, Date value2) {
            addCriterion("deal_time between", value1, value2, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeNotBetween(Date value1, Date value2) {
            addCriterion("deal_time not between", value1, value2, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealWayIsNull() {
            addCriterion("deal_way is null");
            return (Criteria) this;
        }

        public Criteria andDealWayIsNotNull() {
            addCriterion("deal_way is not null");
            return (Criteria) this;
        }

        public Criteria andDealWayEqualTo(String value) {
            addCriterion("deal_way =", value, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayNotEqualTo(String value) {
            addCriterion("deal_way <>", value, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayGreaterThan(String value) {
            addCriterion("deal_way >", value, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayGreaterThanOrEqualTo(String value) {
            addCriterion("deal_way >=", value, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayLessThan(String value) {
            addCriterion("deal_way <", value, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayLessThanOrEqualTo(String value) {
            addCriterion("deal_way <=", value, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayLike(String value) {
            addCriterion("deal_way like", value, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayNotLike(String value) {
            addCriterion("deal_way not like", value, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayIn(List<String> values) {
            addCriterion("deal_way in", values, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayNotIn(List<String> values) {
            addCriterion("deal_way not in", values, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayBetween(String value1, String value2) {
            addCriterion("deal_way between", value1, value2, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealWayNotBetween(String value1, String value2) {
            addCriterion("deal_way not between", value1, value2, "dealWay");
            return (Criteria) this;
        }

        public Criteria andDealResultIsNull() {
            addCriterion("deal_result is null");
            return (Criteria) this;
        }

        public Criteria andDealResultIsNotNull() {
            addCriterion("deal_result is not null");
            return (Criteria) this;
        }

        public Criteria andDealResultEqualTo(String value) {
            addCriterion("deal_result =", value, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultNotEqualTo(String value) {
            addCriterion("deal_result <>", value, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultGreaterThan(String value) {
            addCriterion("deal_result >", value, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultGreaterThanOrEqualTo(String value) {
            addCriterion("deal_result >=", value, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultLessThan(String value) {
            addCriterion("deal_result <", value, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultLessThanOrEqualTo(String value) {
            addCriterion("deal_result <=", value, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultLike(String value) {
            addCriterion("deal_result like", value, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultNotLike(String value) {
            addCriterion("deal_result not like", value, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultIn(List<String> values) {
            addCriterion("deal_result in", values, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultNotIn(List<String> values) {
            addCriterion("deal_result not in", values, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultBetween(String value1, String value2) {
            addCriterion("deal_result between", value1, value2, "dealResult");
            return (Criteria) this;
        }

        public Criteria andDealResultNotBetween(String value1, String value2) {
            addCriterion("deal_result not between", value1, value2, "dealResult");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("COMMENT is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("COMMENT is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("COMMENT =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("COMMENT <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("COMMENT >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENT >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("COMMENT <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("COMMENT <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("COMMENT like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("COMMENT not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("COMMENT in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("COMMENT not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("COMMENT between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("COMMENT not between", value1, value2, "comment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table expense_account_deal
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 29 13:53:03 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}