package com.xuren.oa.entity;

import org.apache.ibatis.type.Alias;

import java.util.Date;

@Alias("ExpenseAccountDeal")
public class ExpenseAccountDeal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_deal.id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_deal.expense_account_id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private Integer expenseAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_deal.deal_sn
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private String dealSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_deal.deal_time
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private Date dealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_deal.deal_way
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private String dealWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_deal.deal_result
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private String dealResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_deal.COMMENT
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_deal.id
     *
     * @return the value of expense_account_deal.id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_deal.id
     *
     * @param id the value for expense_account_deal.id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_deal.expense_account_id
     *
     * @return the value of expense_account_deal.expense_account_id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public Integer getExpenseAccountId() {
        return expenseAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_deal.expense_account_id
     *
     * @param expenseAccountId the value for expense_account_deal.expense_account_id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setExpenseAccountId(Integer expenseAccountId) {
        this.expenseAccountId = expenseAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_deal.deal_sn
     *
     * @return the value of expense_account_deal.deal_sn
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public String getDealSn() {
        return dealSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_deal.deal_sn
     *
     * @param dealSn the value for expense_account_deal.deal_sn
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setDealSn(String dealSn) {
        this.dealSn = dealSn == null ? null : dealSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_deal.deal_time
     *
     * @return the value of expense_account_deal.deal_time
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_deal.deal_time
     *
     * @param dealTime the value for expense_account_deal.deal_time
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_deal.deal_way
     *
     * @return the value of expense_account_deal.deal_way
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public String getDealWay() {
        return dealWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_deal.deal_way
     *
     * @param dealWay the value for expense_account_deal.deal_way
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setDealWay(String dealWay) {
        this.dealWay = dealWay == null ? null : dealWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_deal.deal_result
     *
     * @return the value of expense_account_deal.deal_result
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public String getDealResult() {
        return dealResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_deal.deal_result
     *
     * @param dealResult the value for expense_account_deal.deal_result
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setDealResult(String dealResult) {
        this.dealResult = dealResult == null ? null : dealResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_deal.COMMENT
     *
     * @return the value of expense_account_deal.COMMENT
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_deal.COMMENT
     *
     * @param comment the value for expense_account_deal.COMMENT
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}