package com.xuren.oa.entity;

import org.apache.ibatis.type.Alias;

@Alias("ExpenseAccountDetail")
public class ExpenseAccountDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_detail.id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_detail.expense_account_id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private Integer expenseAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_detail.item
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private String item;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_detail.amount
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_account_detail.COMMENT
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_detail.id
     *
     * @return the value of expense_account_detail.id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_detail.id
     *
     * @param id the value for expense_account_detail.id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_detail.expense_account_id
     *
     * @return the value of expense_account_detail.expense_account_id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public Integer getExpenseAccountId() {
        return expenseAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_detail.expense_account_id
     *
     * @param expenseAccountId the value for expense_account_detail.expense_account_id
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setExpenseAccountId(Integer expenseAccountId) {
        this.expenseAccountId = expenseAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_detail.item
     *
     * @return the value of expense_account_detail.item
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_detail.item
     *
     * @param item the value for expense_account_detail.item
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setItem(String item) {
        this.item = item == null ? null : item.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_detail.amount
     *
     * @return the value of expense_account_detail.amount
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_detail.amount
     *
     * @param amount the value for expense_account_detail.amount
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_account_detail.COMMENT
     *
     * @return the value of expense_account_detail.COMMENT
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_account_detail.COMMENT
     *
     * @param comment the value for expense_account_detail.COMMENT
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}