package com.xuren.oa.mapper;

import com.xuren.oa.entity.ExpenseAccountDetail;
import com.xuren.oa.entity.ExpenseAccountDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpenseAccountDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    long countByExample(ExpenseAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int deleteByExample(ExpenseAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int insert(ExpenseAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int insertSelective(ExpenseAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    List<ExpenseAccountDetail> selectByExample(ExpenseAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    ExpenseAccountDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") ExpenseAccountDetail record, @Param("example") ExpenseAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByExample(@Param("record") ExpenseAccountDetail record, @Param("example") ExpenseAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByPrimaryKeySelective(ExpenseAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_detail
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByPrimaryKey(ExpenseAccountDetail record);
}