package com.xuren.oa.mapper;

import com.xuren.oa.entity.ExpenseAccountDeal;
import com.xuren.oa.entity.ExpenseAccountDealExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpenseAccountDealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    long countByExample(ExpenseAccountDealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int deleteByExample(ExpenseAccountDealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int insert(ExpenseAccountDeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int insertSelective(ExpenseAccountDeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    List<ExpenseAccountDeal> selectByExample(ExpenseAccountDealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    ExpenseAccountDeal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") ExpenseAccountDeal record, @Param("example") ExpenseAccountDealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByExample(@Param("record") ExpenseAccountDeal record, @Param("example") ExpenseAccountDealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByPrimaryKeySelective(ExpenseAccountDeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account_deal
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByPrimaryKey(ExpenseAccountDeal record);
}