package com.xuren.oa.mapper;

import com.xuren.oa.entity.ExpenseAccount;
import com.xuren.oa.entity.ExpenseAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpenseAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    long countByExample(ExpenseAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int deleteByExample(ExpenseAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int insert(ExpenseAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int insertSelective(ExpenseAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    List<ExpenseAccount> selectByExample(ExpenseAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    ExpenseAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") ExpenseAccount record, @Param("example") ExpenseAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByExample(@Param("record") ExpenseAccount record, @Param("example") ExpenseAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByPrimaryKeySelective(ExpenseAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_account
     *
     * @mbg.generated Mon Jul 29 13:53:03 CST 2019
     */
    int updateByPrimaryKey(ExpenseAccount record);
}